package nl.michielgraat.synacor;

public class Solution {
    public static String[] commands = {
        "take tablet\n",
        "use tablet\n",
        "drop tablet\n",
        "go doorway\n",
        "go north\n",
        "go north\n",
        "go bridge\n",
        "go continue\n",
        "go down\n",
        "go east\n",
        "take empty lantern\n",
        "go west\n",
        "go west\n",
        "go passage\n",
        "go ladder\n",
        "go west\n",
        "go south\n",
        "go north\n",
        "take can\n",
        "use can\n",
        "use lantern\n",
        "go west\n",
        "go ladder\n",
        "go darkness\n",
        "go continue\n",
        "go west\n",
        "go west\n",
        "go west\n",
        "go west\n",
        "go north\n",
        "take red coin\n",
        "look red coin\n",
        "go north\n",
        "go east\n",
        "take concave coin\n",
        "look concave coin\n",
        "go down\n",
        "take corroded coin\n",
        "look corroded coin\n",
        "go up\n",
        "go west\n",
        "go west\n",
        "take blue coin\n",
        "look blue coin\n",
        "go up\n",
        "take shiny coin\n",
        "look shiny coin\n",
        "go down\n",
        "go east\n",
        "use blue coin\n",
        "use red coin\n",
        "use shiny coin\n",
        "use concave coin\n",
        "use corroded coin\n",
        "go north\n",
        "take teleporter\n",
        "use teleporter\n",
        "take business card\n",
        "look business card\n",
        "take strange book\n",
        "look strange book\n"
    };
}
